version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
